---
- name: Install and configure Chrony using variables
  hosts: all
  become: yes
  vars:
    chrony_package: ""
    chrony_service: "chronyd"
    chrony_confdir: "/etc/chrony.conf"  # Modifié ici

  tasks:
    - name: Set package name based on distribution
      set_fact:
        chrony_package: "{{ 'chrony' if ansible_os_family == 'Debian' else 'chrony' if ansible_distribution == 'Rocky' else 'chrony' if ansible_os_family == 'Suse' else 'chrony' }}"

    - name: Install Chrony
      package:
        name: "{{ chrony_package }}"
        state: present

    - name: Configure Chrony
      copy:
        dest: "{{ chrony_confdir }}"
        content: |
          server 0.fr.pool.ntp.org iburst
          server 1.fr.pool.ntp.org iburst
          server 2.fr.pool.ntp.org iburst
          server 3.fr.pool.ntp.org iburst
          driftfile /var/lib/chrony/drift
          makestep 1.0 3
          rtcsync
          logdir /var/log/chrony
      notify: Restart chronyd

  handlers:
    - name: Restart chronyd
      service:
        name: "{{ chrony_service }}"
        state: restarted

