---
- hosts: all
  tasks:
    - name: Set favorite car and bike
      set_fact:
        mycar: LAMBO
        mybike: Yamaha

    - name: Display favorite car and bike
      debug:
        msg: "Ma voiture préféré est la {{ mycar }} et ma moto favorite est une {{ mybike }}."

