---
- name: Afficher le nombre total de paquets RPM installés
  hosts: rocky,suse
  gather_facts: no
  tasks:
    - name: Lister les paquets RPM installés
      shell: rpm -qa
      register: rpm_list

    - name: Compter le nombre de paquets RPM installés
      set_fact:
        rpm_count: "{{ rpm_list.stdout_lines | length }}"

    - name: Afficher le nombre total de paquets RPM
      debug:
        msg: "Nombre total de paquets RPM installés sur {{ inventory_hostname }} : {{ rpm_count }}"


