---
- hosts: all
  vars_files:
    - vars/default_vars.yml

  tasks:
    - name: Display favorite car and bike
      debug:
        msg: "Ma voiture préféré est la {{ mycar }} et ma moto favorite est une {{ mybike }}."

