- hosts: suse
  become: yes

  tasks:
    - name: Install Apache
      zypper:
        name: apache2
        state: present

    - name: Start and enable Apache
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Copy custom index.html
      copy:
        content: |
          <html>
            <head>
              <title>Apache Web Server on SUSE Linux</title>
            </head>
            <body>
              <h1>Apache Web Server running on SUSE Linux</h1>
            </body>
          </html>
        dest: /srv/www/htdocs/index.html


