---
- name: Afficher les serveurs DNS utilisés
  hosts: all
  gather_facts: no
  tasks:
    - name: Lire le fichier de configuration des résolveurs DNS
      command: cat /etc/resolv.conf
      register: dns_info
      ignore_errors: yes

    - name: Extraire les serveurs DNS
      set_fact:
        dns_servers: "{{ dns_info.stdout_lines | select('match', '^nameserver') | map('regex_replace', '^nameserver\\s+', '') | list }}"

    - name: Afficher les serveurs DNS
      debug:
        msg: "Serveurs DNS utilisés sur {{ inventory_hostname }} : {{ dns_servers | join(', ') | default('Aucun serveur DNS trouvé') }}"

