---
- name: Afficher le gestionnaire de paquets utilisé
  hosts: all
  gather_facts: no
  tasks:
    - name: Déterminer le gestionnaire de paquets
      shell: |
        if command -v apt > /dev/null; then
          echo "apt"
        elif command -v dnf > /dev/null; then
          echo "dnf"
        elif command -v yum > /dev/null; then
          echo "yum"
        elif command -v zypper > /dev/null; then
          echo "zypper"
        else
          echo "Aucun gestionnaire de paquets trouvé"
        fi
      register: pkg_manager

    - name: Afficher le gestionnaire de paquets
      debug:
        msg: "Gestionnaire de paquets utilisé sur {{ inventory_hostname }} : {{ pkg_manager.stdout }}"

