---
- name: Installer et configurer Chrony
  hosts: all
  become: yes
  vars:
    chrony_conf_path: "/etc/chrony.conf"  # Chemin standard pour toutes les distributions

  tasks:
    - name: Installer le paquet Chrony
      package:
        name: chrony
        state: present

    - name: Déployer le fichier de configuration Chrony
      copy:
        dest: "{{ chrony_conf_path }}"
        content: |
          # Chemin vers le fichier de configuration : {{ chrony_conf_path }}
          server 0.fr.pool.ntp.org iburst
          server 1.fr.pool.ntp.org iburst
          server 2.fr.pool.ntp.org iburst
          server 3.fr.pool.ntp.org iburst
          driftfile /var/lib/chrony/drift
          makestep 1.0 3
          rtcsync
          logdir /var/log/chrony
      notify: Restart chronyd

  handlers:
    - name: Restart chronyd
      service:
        name: chronyd
        state: restarted

